cert-manager:

  installCRDs: true
  prometheus:
    servicemonitor:
      enabled: false

  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

  webhook:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi
  
  cainjector:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi

  startupapicheck:
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 128Mi

# TODO Add comments about these values below
schtack:

  additionalLabels: {}

  clusterIssuers:

    selfSignedCerts:
      enabled: true
      name: selfsigned-issuer

    # TODO Add the ExternalSecret object to get the CA key pair from the external secret store
    selfSignedCA:
      enabled: false
      name: selfsigned-ca-issuer
      secretName: self-signed-ca-key-pair
    
    letsencrypt:
      enabled: false
      acmeSolvers:
      # TODO Add support for the acme solver configuration in the Let's Encrypt cluster issuers
      - http01:
          ingress: {}
      issuers:
      - name: letsencrypt-staging-issuer
        email: letsencrypt@example.org
        server: https://acme-staging-v02.api.letsencrypt.org/directory
      - name: letsencrypt-production-issuer
        email: letsencrypt@example.org
        server: https://acme-v02.api.letsencrypt.org/directory
